### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ZeenatLawal** [enkog/Penz_Classes_Backend#39]
Hello, There are 4 people on our team. [Elyor Doniyorov](https://github.com/elyor-doniyorov), [Priscilla Olajumoke Oni](https://github.com/prolajumokeoni), [Oguadinma Nkiruka Ngozika](https://github.com/enkog) and [Zeenat Lawal](https://github.com/ZeenatLawal).

[Link to Project](https://github.com/enkog/Final_Group_Project_Backend/projects/1)

![FireShot Capture 146 - Final Group Project - github com](https://user-images.githubusercontent.com/46851023/141288854-34cb1902-4c16-498a-974f-cabff53309a2.png)

**Comment by SpaYco** [comment]
Hi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't include:

- link to your GitHub project (frontend/backend)
- information about the number of people in your group

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ZeenatLawal** [comment]
> Hi,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that doesn't include:
> 
> * link to your GitHub project (frontend/backend)
> * information about the number of people in your group
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

Hello @SpaYco, based on the requirements we are to create an issue with the following:
- In its description, paste a link to your GitHub project.
- Add a note telling the reviewer how many people there are in your team.
- Take a screenshot of your board and add it to your issue's description (do it before each review to always have the freshest version of your board). You will need it for the final evaluation.

And these are provided above. Thanks

**Comment by AdnanAfsari** [comment]
Hi @ZeenatLawal @enkog @elyor-doniyorov @prolajumokeoni , 

In my opinion,  There is nothing else to say other than... it's time to move to the next step :-)


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
